# Generated by Django 5.1.5 on 2025-02-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-f_actualizacion']},
        ),
    ]
