# Generated by Django 5.1.5 on 2025-02-24 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_carrito_total'),
        ('productos', '0004_alter_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosFavoritos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos_asociados', to='clientes.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_favoritas', to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos', through='productos.ProductosFavoritos', to='clientes.cliente'),
        ),
        migrations.AddConstraint(
            model_name='productosfavoritos',
            constraint=models.UniqueConstraint(fields=('cliente', 'producto'), name='unique_cliente_producto_favorito'),
        ),
    ]
