# Generated by Django 5.1.5 on 2025-03-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_productosfavoritos_producto_favoritos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosfavoritos',
            options={'ordering': ['-f_creacion']},
        ),
    ]
