# Generated by Django 5.1.5 on 2025-02-20 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_remove_carrito_cantidad_remove_carrito_producto_and_more'),
        ('productos', '0004_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'verbose_name': 'Detalle de Orden', 'verbose_name_plural': 'Detalles de Orden'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-f_creacion'], 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ordenes.orden'),
        ),
        migrations.AddConstraint(
            model_name='detalleorden',
            constraint=models.UniqueConstraint(fields=('orden', 'producto'), name='unique_detalle'),
        ),
    ]
