# Generated by Django 5.1.5 on 2025-02-21 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Item de Carrito'},
        ),
    ]
