# Generated by Django 5.1.5 on 2025-02-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_carrito_cliente'),
        ('productos', '0004_alter_producto_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'producto'), name='unique_item'),
        ),
    ]
