# Generated by Django 5.1.5 on 2025-02-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_itemcarrito_unique_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveBigIntegerField(),
        ),
    ]
