# Generated by Django 5.1.5 on 2025-02-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_itemcarrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
