# Generated by Django 5.1.5 on 2025-02-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_itemcarrito_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
